USE [master]
GO

/****** Object:  Database [emb]    Script Date: 05/07/2014 13:54:35 ******/
CREATE DATABASE [emb] ON  PRIMARY 
( NAME = N'EAB', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10_50.TIANYX\MSSQL\DATA\emb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EAB_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10_50.TIANYX\MSSQL\DATA\emb_1.ldf' , SIZE = 6912KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [emb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [emb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [emb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [emb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [emb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [emb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [emb] SET ARITHABORT OFF 
GO

ALTER DATABASE [emb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [emb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [emb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [emb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [emb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [emb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [emb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [emb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [emb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [emb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [emb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [emb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [emb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [emb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [emb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [emb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [emb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [emb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [emb] SET  READ_WRITE 
GO

ALTER DATABASE [emb] SET RECOVERY FULL 
GO

ALTER DATABASE [emb] SET  MULTI_USER 
GO

ALTER DATABASE [emb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [emb] SET DB_CHAINING OFF 
GO

