/* clipservice.h
   Generated by wsdl2h 1.2.13 from clipservice.wsdl and typemap.dat
   2014-05-12 02:22:12 GMT
   gSOAP XML Web services tools.
   Copyright (C) 2001-2009 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * http://219.232.52.76:8084/WebSrv/FounderService.asmx                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to disable)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

CLIPSVR = "http://219.232.52.76:8084/WebSrv/FounderService.asmx"
ns1 = "http://JSTV/PublicService/Parameter/"

*/

//gsoap CLIPSVR schema namespace:	http://219.232.52.76:8084/WebSrv/FounderService.asmx
//gsoap ns1   schema namespace:	http://JSTV/PublicService/Parameter/
//gsoap CLIPSVR schema elementForm:	qualified
//gsoap CLIPSVR schema attributeForm:	unqualified
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class CLIPSVR__OutMessage.
class CLIPSVR__OutMessage;

//  Forward declaration of class CLIPSVR__ArrayOfOutMessageFile.
class CLIPSVR__ArrayOfOutMessageFile;

//  Forward declaration of class CLIPSVR__OutMessageFile.
class CLIPSVR__OutMessageFile;

//  Forward declaration of class CLIPSVR__ArrayOfBreakPoint.
class CLIPSVR__ArrayOfBreakPoint;

//  Forward declaration of class CLIPSVR__BreakPoint.
class CLIPSVR__BreakPoint;

//  Forward declaration of class CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute.
class CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute;

//  Forward declaration of class CLIPSVR__StatusDesc.
class CLIPSVR__StatusDesc;

//  Forward declaration of class CLIPSVR__ArrayOfProgramBasicEntityType.
class CLIPSVR__ArrayOfProgramBasicEntityType;

//  Forward declaration of class _CLIPSVR__OutStorageFunction.
class _CLIPSVR__OutStorageFunction;

//  Forward declaration of class _CLIPSVR__OutStorageFunctionResponse.
class _CLIPSVR__OutStorageFunctionResponse;

//  Forward declaration of class _CLIPSVR__TransferTaskExcuteResultNotify.
class _CLIPSVR__TransferTaskExcuteResultNotify;

//  Forward declaration of class _CLIPSVR__TransferTaskExcuteResultNotifyResponse.
class _CLIPSVR__TransferTaskExcuteResultNotifyResponse;

//  Forward declaration of class _CLIPSVR__MaterialQuery.
class _CLIPSVR__MaterialQuery;

//  Forward declaration of class _CLIPSVR__MaterialQueryResponse.
class _CLIPSVR__MaterialQueryResponse;

//  Forward declaration of class _CLIPSVR__ClipIsExistQuery.
class _CLIPSVR__ClipIsExistQuery;

//  Forward declaration of class _CLIPSVR__ClipIsExistQueryResponse.
class _CLIPSVR__ClipIsExistQueryResponse;

//  Forward declaration of class _CLIPSVR__QueryCache.
class _CLIPSVR__QueryCache;

//  Forward declaration of class _CLIPSVR__QueryCacheResponse.
class _CLIPSVR__QueryCacheResponse;

//  Forward declaration of class ns1__ProgramBasicEntityType.
class ns1__ProgramBasicEntityType;

//  Forward declaration of class _ns1__MaterialQueryRequest.
class _ns1__MaterialQueryRequest;

//  Forward declaration of class _ns1__ClipExistQueryRequest.
class _ns1__ClipExistQueryRequest;

//  Forward declaration of class _ns1__ClipIsExistQueryResult.
class _ns1__ClipIsExistQueryResult;

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutMessage is a complexType.
class CLIPSVR__OutMessage
{ public:
/// Element programID of type xs:string.
    std::string*                         programID                      0;	///< Optional element.
/// Element programName of type xs:string.
    std::string*                         programName                    0;	///< Optional element.
/// Element playDate of type xs:dateTime.
    time_t*                              playDate                       1;	///< Nullable pointer.
/// Element channelId of type xs:string.
    std::string*                         channelId                      0;	///< Optional element.
/// Element clipType of type xs:string.
    std::string*                         clipType                       0;	///< Optional element.
/// Element HD of type xs:int.
    int*                                 HD                             1;	///< Nullable pointer.
/// Element startpoint of type xs:int.
    int*                                 startpoint                     1;	///< Nullable pointer.
/// Element endpoint of type xs:int.
    int*                                 endpoint                       1;	///< Nullable pointer.
/// Element length of type xs:int.
    int*                                 length                         1;	///< Nullable pointer.
/// Element fileList of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfOutMessageFile.
    CLIPSVR__ArrayOfOutMessageFile*      fileList                       0;	///< Optional element.
/// Element ip of type xs:string.
    std::string*                         ip                             0;	///< Optional element.
/// Element path of type xs:string.
    std::string*                         path                           0;	///< Optional element.
/// Element port of type xs:int.
    int                                  port                           1;	///< Required element.
/// Element user of type xs:string.
    std::string*                         user                           0;	///< Optional element.
/// Element pass of type xs:string.
    std::string*                         pass                           0;	///< Optional element.
/// Element callbackurl of type xs:string.
    std::string*                         callbackurl                    0;	///< Optional element.
/// Element emerg of type xs:string.
    std::string*                         emerg                          0;	///< Optional element.
/// Element SourceID of type xs:string.
    std::string*                         SourceID                       0;	///< Optional element.
/// Element BreakPointList of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfBreakPoint.
    CLIPSVR__ArrayOfBreakPoint*          BreakPointList                 0;	///< Optional element.
/// Element ExtendAttributes of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfExtentionAttributeTypeExtentionAttribute.
    CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute*  ExtendAttributes               0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfOutMessageFile is a complexType.
class CLIPSVR__ArrayOfOutMessageFile
{ public:
/// Vector of CLIPSVR__OutMessageFile* with length 0..unbounded
    std::vector<CLIPSVR__OutMessageFile*> OutMessageFile                 0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutMessageFile is a complexType.
class CLIPSVR__OutMessageFile
{ public:
/// Element md5 of type xs:string.
    std::string*                         md5                            0;	///< Optional element.
/// Element name of type xs:string.
    std::string*                         name                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfBreakPoint is a complexType.
class CLIPSVR__ArrayOfBreakPoint
{ public:
/// Vector of CLIPSVR__BreakPoint* with length 0..unbounded
    std::vector<CLIPSVR__BreakPoint*   > BreakPoints                    0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":BreakPoint is a complexType.
class CLIPSVR__BreakPoint
{ public:
/// Element PointLocation of type xs:int.
    int*                                 PointLocation                  0;	///< Optional element.
/// Element Description of type xs:string.
    std::string*                         Description                    0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfExtentionAttributeTypeExtentionAttribute is a complexType.
class CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute
{ public:
/// Size of ExtentionAttribute array is 0..unbounded
    int                                  __sizeExtentionAttribute      ;
    class _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute
    {
/// Element ItemCode of type xs:string.
    std::string*                         ItemCode                       0;	///< Optional element.
/// Element ItemName of type xs:string.
    std::string*                         ItemName                       0;	///< Optional element.
/// Element Value of type xs:string.
    std::string*                         Value                          0;	///< Optional element.
    }                                   *ExtentionAttribute             0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":StatusDesc is a complexType.
class CLIPSVR__StatusDesc
{ public:
/// Element code of type xs:string.
    std::string*                         code                           0;	///< Optional element.
/// Element desc of type xs:string.
    std::string*                         desc                           0;	///< Optional element.
/// Element retry of type xs:int.
    int                                  retry                          1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfProgramBasicEntityType is a complexType.
class CLIPSVR__ArrayOfProgramBasicEntityType
{ public:
/// Vector of ns1__ProgramBasicEntityType* with length 0..unbounded
    std::vector<ns1__ProgramBasicEntityType*> ProgramBasicEntityType         0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutStorageFunction of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutStorageFunction is a complexType.
class _CLIPSVR__OutStorageFunction
{ public:
/// Element massageparam of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutMessage.
    CLIPSVR__OutMessage*                 massageparam                   0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutStorageFunctionResponse of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":OutStorageFunctionResponse is a complexType.
class _CLIPSVR__OutStorageFunctionResponse
{ public:
/// Element OutStorageFunctionResponse of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":StatusDesc.
    CLIPSVR__StatusDesc*                 OutStorageFunctionResponse     0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":TransferTaskExcuteResultNotify of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":TransferTaskExcuteResultNotify is a complexType.
class _CLIPSVR__TransferTaskExcuteResultNotify
{ public:
/// Element ResultXML of type xs:string.
    std::string*                         ResultXML                      0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":TransferTaskExcuteResultNotifyResponse of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":TransferTaskExcuteResultNotifyResponse is a complexType.
class _CLIPSVR__TransferTaskExcuteResultNotifyResponse
{ public:
/// Element TransferTaskExcuteResultNotifyResult of type xs:boolean.
    bool                                 TransferTaskExcuteResultNotifyResult 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":MaterialQuery of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":MaterialQuery is a complexType.
class _CLIPSVR__MaterialQuery
{ public:
/// Element reference "http://JSTV/PublicService/Parameter/":MaterialQueryRequest.
    _ns1__MaterialQueryRequest*          ns1__MaterialQueryRequest      1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":MaterialQueryResponse of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":MaterialQueryResponse is a complexType.
class _CLIPSVR__MaterialQueryResponse
{ public:
/// Element MaterialQueryResult of type "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ArrayOfProgramBasicEntityType.
    CLIPSVR__ArrayOfProgramBasicEntityType*  MaterialQueryResult            0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ClipIsExistQuery of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ClipIsExistQuery is a complexType.
class _CLIPSVR__ClipIsExistQuery
{ public:
/// Element reference "http://JSTV/PublicService/Parameter/":ClipExistQueryRequest.
    _ns1__ClipExistQueryRequest*         ns1__ClipExistQueryRequest     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ClipIsExistQueryResponse of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":ClipIsExistQueryResponse is a complexType.
class _CLIPSVR__ClipIsExistQueryResponse
{ public:
/// Element reference "http://JSTV/PublicService/Parameter/":ClipIsExistQueryResult.
    _ns1__ClipIsExistQueryResult*        ns1__ClipIsExistQueryResult    1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":QueryCache of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":QueryCache is a complexType.
class _CLIPSVR__QueryCache
{ public:
/// Element paramIn of type xs:string.
    std::string*                         paramIn                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":QueryCacheResponse of complexType.

/// "http://219.232.52.76:8084/WebSrv/FounderService.asmx":QueryCacheResponse is a complexType.
class _CLIPSVR__QueryCacheResponse
{ public:
/// Element QueryCacheResult of type xs:string.
    std::string*                         QueryCacheResult               0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://JSTV/PublicService/Parameter/":ProgramBasicEntityType is a complexType.
class ns1__ProgramBasicEntityType
{ public:
/// Element ProgramCode of type xs:string.
    std::string*                         ProgramCode                    0;	///< Optional element.
/// Element ProgramName of type xs:string.
    std::string*                         ProgramName                    0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://JSTV/PublicService/Parameter/":MaterialQueryRequest of complexType.

/// "http://JSTV/PublicService/Parameter/":MaterialQueryRequest is a complexType.
class _ns1__MaterialQueryRequest
{ public:
    class _ns1__MaterialQueryRequest_PlanAirDate
    {
/// Element From of type xs:string.
    std::string*                         From                           0;	///< Optional element.
/// Element To of type xs:string.
    std::string*                         To                             0;	///< Optional element.
    }                                   *PlanAirDate                    1;	///< Nullable pointer.
/// Element ChannelID of type xs:string.
    std::string*                         ChannelID                      1;	///< Nullable pointer.
/// Element ProgramNameKeyWord of type xs:string.
    std::string*                         ProgramNameKeyWord             1;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://JSTV/PublicService/Parameter/":ClipExistQueryRequest of complexType.

/// "http://JSTV/PublicService/Parameter/":ClipExistQueryRequest is a complexType.
class _ns1__ClipExistQueryRequest
{ public:
/// Size of ClipArray array is 0..unbounded
    int                                  __sizeClipArray               ;
    class _ns1__ClipExistQueryRequest_ClipArray
    {
/// Element ClipPrimaryID of type xs:string.
    std::string*                         ClipPrimaryID                  1;	///< Nullable pointer.
    }                                   *ClipArray                      0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://JSTV/PublicService/Parameter/":ClipIsExistQueryResult of complexType.

/// "http://JSTV/PublicService/Parameter/":ClipIsExistQueryResult is a complexType.
class _ns1__ClipIsExistQueryResult
{ public:
/// Size of ClipArrayResult array is 0..unbounded
    int                                  __sizeClipArrayResult         ;
    class _ns1__ClipIsExistQueryResult_ClipArrayResult
    {
    class _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem
    {
/// Element ClipPrimaryID of type xs:string.
    std::string*                         ClipPrimaryID                  1;	///< Nullable pointer.
    }                                   *ClipItem                       1;	///< Nullable pointer.
/// Element IsExist of type xs:boolean.
    bool                                 IsExist                        1;	///< Required element.
/// Element Statue of type xs:int.
    int                                  Statue                         1;	///< Required element.
/// Element Description of type xs:string.
    std::string*                         Description                    1;	///< Nullable pointer.
    }                                   *ClipArrayResult                0;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":boolean of type xs:boolean.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://219.232.52.76:8084/WebSrv/FounderService.asmx":string of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap CLIPSVR2 service name:	ClipServiceSoap 
//gsoap CLIPSVR2 service type:	ClipServiceSoap 
//gsoap CLIPSVR2 service port:	http://localhost:6477/clipservice.asmx 
//gsoap CLIPSVR2 service namespace:	http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipServiceSoap 
//gsoap CLIPSVR2 service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap CLIPSVR3 service name:	ClipServiceSoap12 
//gsoap CLIPSVR3 service type:	ClipServiceSoap 
//gsoap CLIPSVR3 service port:	http://localhost:6477/clipservice.asmx 
//gsoap CLIPSVR3 service namespace:	http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipServiceSoap12 
//gsoap CLIPSVR3 service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref ClipServiceSoap
  - @ref ClipServiceSoap12

*/

/**

@page ClipServiceSoap Binding "ClipServiceSoap"

@section ClipServiceSoap_operations Operations of Binding  "ClipServiceSoap"
  - @ref __CLIPSVR2__OutStorageFunction
  - @ref __CLIPSVR2__TransferTaskExcuteResultNotify
  - @ref __CLIPSVR2__MaterialQuery
  - @ref __CLIPSVR2__ClipIsExistQuery
  - @ref __CLIPSVR2__QueryCache

@section ClipServiceSoap_ports Endpoints of Binding  "ClipServiceSoap"
  - http://localhost:6477/clipservice.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page ClipServiceSoap12 Binding "ClipServiceSoap12"

@section ClipServiceSoap12_operations Operations of Binding  "ClipServiceSoap12"
  - @ref __CLIPSVR3__OutStorageFunction
  - @ref __CLIPSVR3__TransferTaskExcuteResultNotify
  - @ref __CLIPSVR3__MaterialQuery
  - @ref __CLIPSVR3__ClipIsExistQuery
  - @ref __CLIPSVR3__QueryCache

@section ClipServiceSoap12_ports Endpoints of Binding  "ClipServiceSoap12"
  - http://localhost:6477/clipservice.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * ClipServiceSoap                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __CLIPSVR2__OutStorageFunction                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR2__OutStorageFunction" of service binding "ClipServiceSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/OutStorageFunction"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR2__OutStorageFunction(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,
    // response parameters:
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR2__OutStorageFunction(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,
    // response parameters:
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoapProxy.h):
  class ClipServiceSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR2 service method-style:	OutStorageFunction document
//gsoap CLIPSVR2 service method-encoding:	OutStorageFunction literal
//gsoap CLIPSVR2 service method-action:	OutStorageFunction http://219.232.52.76:8084/WebSrv/FounderService.asmx/OutStorageFunction
int __CLIPSVR2__OutStorageFunction(
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,	///< Request parameter
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR2__TransferTaskExcuteResultNotify                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR2__TransferTaskExcuteResultNotify" of service binding "ClipServiceSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/TransferTaskExcuteResultNotify"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR2__TransferTaskExcuteResultNotify(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,
    // response parameters:
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR2__TransferTaskExcuteResultNotify(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,
    // response parameters:
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoapProxy.h):
  class ClipServiceSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR2 service method-style:	TransferTaskExcuteResultNotify document
//gsoap CLIPSVR2 service method-encoding:	TransferTaskExcuteResultNotify literal
//gsoap CLIPSVR2 service method-action:	TransferTaskExcuteResultNotify http://219.232.52.76:8084/WebSrv/FounderService.asmx/TransferTaskExcuteResultNotify
int __CLIPSVR2__TransferTaskExcuteResultNotify(
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,	///< Request parameter
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR2__MaterialQuery                                                  *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR2__MaterialQuery" of service binding "ClipServiceSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/MaterialQuery"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR2__MaterialQuery(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,
    // response parameters:
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR2__MaterialQuery(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,
    // response parameters:
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoapProxy.h):
  class ClipServiceSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR2 service method-style:	MaterialQuery document
//gsoap CLIPSVR2 service method-encoding:	MaterialQuery literal
//gsoap CLIPSVR2 service method-action:	MaterialQuery http://219.232.52.76:8084/WebSrv/FounderService.asmx/MaterialQuery
int __CLIPSVR2__MaterialQuery(
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,	///< Request parameter
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR2__ClipIsExistQuery                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR2__ClipIsExistQuery" of service binding "ClipServiceSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipIsExistQuery"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR2__ClipIsExistQuery(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,
    // response parameters:
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR2__ClipIsExistQuery(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,
    // response parameters:
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoapProxy.h):
  class ClipServiceSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR2 service method-style:	ClipIsExistQuery document
//gsoap CLIPSVR2 service method-encoding:	ClipIsExistQuery literal
//gsoap CLIPSVR2 service method-action:	ClipIsExistQuery http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipIsExistQuery
int __CLIPSVR2__ClipIsExistQuery(
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,	///< Request parameter
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR2__QueryCache                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR2__QueryCache" of service binding "ClipServiceSoap"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/QueryCache"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR2__QueryCache(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,
    // response parameters:
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR2__QueryCache(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,
    // response parameters:
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoapProxy.h):
  class ClipServiceSoap;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR2 service method-style:	QueryCache document
//gsoap CLIPSVR2 service method-encoding:	QueryCache literal
//gsoap CLIPSVR2 service method-action:	QueryCache http://219.232.52.76:8084/WebSrv/FounderService.asmx/QueryCache
int __CLIPSVR2__QueryCache(
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,	///< Request parameter
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ClipServiceSoap12                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __CLIPSVR3__OutStorageFunction                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR3__OutStorageFunction" of service binding "ClipServiceSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/OutStorageFunction"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR3__OutStorageFunction(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,
    // response parameters:
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR3__OutStorageFunction(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,
    // response parameters:
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoap12Proxy.h):
  class ClipServiceSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR3 service method-style:	OutStorageFunction document
//gsoap CLIPSVR3 service method-encoding:	OutStorageFunction literal
//gsoap CLIPSVR3 service method-action:	OutStorageFunction http://219.232.52.76:8084/WebSrv/FounderService.asmx/OutStorageFunction
int __CLIPSVR3__OutStorageFunction(
    _CLIPSVR__OutStorageFunction*       CLIPSVR__OutStorageFunction,	///< Request parameter
    _CLIPSVR__OutStorageFunctionResponse* CLIPSVR__OutStorageFunctionResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR3__TransferTaskExcuteResultNotify                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR3__TransferTaskExcuteResultNotify" of service binding "ClipServiceSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/TransferTaskExcuteResultNotify"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR3__TransferTaskExcuteResultNotify(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,
    // response parameters:
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR3__TransferTaskExcuteResultNotify(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,
    // response parameters:
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoap12Proxy.h):
  class ClipServiceSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR3 service method-style:	TransferTaskExcuteResultNotify document
//gsoap CLIPSVR3 service method-encoding:	TransferTaskExcuteResultNotify literal
//gsoap CLIPSVR3 service method-action:	TransferTaskExcuteResultNotify http://219.232.52.76:8084/WebSrv/FounderService.asmx/TransferTaskExcuteResultNotify
int __CLIPSVR3__TransferTaskExcuteResultNotify(
    _CLIPSVR__TransferTaskExcuteResultNotify* CLIPSVR__TransferTaskExcuteResultNotify,	///< Request parameter
    _CLIPSVR__TransferTaskExcuteResultNotifyResponse* CLIPSVR__TransferTaskExcuteResultNotifyResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR3__MaterialQuery                                                  *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR3__MaterialQuery" of service binding "ClipServiceSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/MaterialQuery"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR3__MaterialQuery(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,
    // response parameters:
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR3__MaterialQuery(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,
    // response parameters:
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoap12Proxy.h):
  class ClipServiceSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR3 service method-style:	MaterialQuery document
//gsoap CLIPSVR3 service method-encoding:	MaterialQuery literal
//gsoap CLIPSVR3 service method-action:	MaterialQuery http://219.232.52.76:8084/WebSrv/FounderService.asmx/MaterialQuery
int __CLIPSVR3__MaterialQuery(
    _CLIPSVR__MaterialQuery*            CLIPSVR__MaterialQuery,	///< Request parameter
    _CLIPSVR__MaterialQueryResponse*    CLIPSVR__MaterialQueryResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR3__ClipIsExistQuery                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR3__ClipIsExistQuery" of service binding "ClipServiceSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipIsExistQuery"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR3__ClipIsExistQuery(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,
    // response parameters:
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR3__ClipIsExistQuery(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,
    // response parameters:
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoap12Proxy.h):
  class ClipServiceSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR3 service method-style:	ClipIsExistQuery document
//gsoap CLIPSVR3 service method-encoding:	ClipIsExistQuery literal
//gsoap CLIPSVR3 service method-action:	ClipIsExistQuery http://219.232.52.76:8084/WebSrv/FounderService.asmx/ClipIsExistQuery
int __CLIPSVR3__ClipIsExistQuery(
    _CLIPSVR__ClipIsExistQuery*         CLIPSVR__ClipIsExistQuery,	///< Request parameter
    _CLIPSVR__ClipIsExistQueryResponse* CLIPSVR__ClipIsExistQueryResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __CLIPSVR3__QueryCache                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__CLIPSVR3__QueryCache" of service binding "ClipServiceSoap12"

/**

Operation details:

  - SOAP document/literal style
  - SOAP action="http://219.232.52.76:8084/WebSrv/FounderService.asmx/QueryCache"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___CLIPSVR3__QueryCache(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,
    // response parameters:
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __CLIPSVR3__QueryCache(
    struct soap *soap,
    // request parameters:
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,
    // response parameters:
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse
  );
@endcode

C++ proxy class (defined in soapClipServiceSoap12Proxy.h):
  class ClipServiceSoap12;

Note: use soapcpp2 option '-i' to generate improved proxy and service classes;

*/

//gsoap CLIPSVR3 service method-style:	QueryCache document
//gsoap CLIPSVR3 service method-encoding:	QueryCache literal
//gsoap CLIPSVR3 service method-action:	QueryCache http://219.232.52.76:8084/WebSrv/FounderService.asmx/QueryCache
int __CLIPSVR3__QueryCache(
    _CLIPSVR__QueryCache*               CLIPSVR__QueryCache,	///< Request parameter
    _CLIPSVR__QueryCacheResponse*       CLIPSVR__QueryCacheResponse	///< Response parameter
);

/* End of clipservice.h */
