/* soapH.h
   Generated by gSOAP 2.7.13 from clipservice.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem
#define SOAP_TYPE__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem (59)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, const char*, int, const _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem * SOAP_FMAC4 soap_get__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem * SOAP_FMAC4 soap_in__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, const char*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *, const char*);

#define soap_new__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(soap, n) soap_instantiate__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem * SOAP_FMAC4 soap_instantiate__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ClipIsExistQueryResult_ClipArrayResult
#define SOAP_TYPE__ns1__ClipIsExistQueryResult_ClipArrayResult (58)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, const char*, int, const _ns1__ClipIsExistQueryResult_ClipArrayResult *, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult * SOAP_FMAC4 soap_get__ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult *, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult * SOAP_FMAC4 soap_in__ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, const char*, _ns1__ClipIsExistQueryResult_ClipArrayResult *, const char*);

#define soap_new__ns1__ClipIsExistQueryResult_ClipArrayResult(soap, n) soap_instantiate__ns1__ClipIsExistQueryResult_ClipArrayResult(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ClipIsExistQueryResult_ClipArrayResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult * SOAP_FMAC4 soap_instantiate__ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ClipExistQueryRequest_ClipArray
#define SOAP_TYPE__ns1__ClipExistQueryRequest_ClipArray (56)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ClipExistQueryRequest_ClipArray(struct soap*, const char*, int, const _ns1__ClipExistQueryRequest_ClipArray *, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest_ClipArray * SOAP_FMAC4 soap_get__ns1__ClipExistQueryRequest_ClipArray(struct soap*, _ns1__ClipExistQueryRequest_ClipArray *, const char*, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest_ClipArray * SOAP_FMAC4 soap_in__ns1__ClipExistQueryRequest_ClipArray(struct soap*, const char*, _ns1__ClipExistQueryRequest_ClipArray *, const char*);

#define soap_new__ns1__ClipExistQueryRequest_ClipArray(soap, n) soap_instantiate__ns1__ClipExistQueryRequest_ClipArray(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ClipExistQueryRequest_ClipArray(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ClipExistQueryRequest_ClipArray * SOAP_FMAC4 soap_instantiate__ns1__ClipExistQueryRequest_ClipArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ClipExistQueryRequest_ClipArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__MaterialQueryRequest_PlanAirDate
#define SOAP_TYPE__ns1__MaterialQueryRequest_PlanAirDate (54)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__MaterialQueryRequest_PlanAirDate(struct soap*, const char*, int, const _ns1__MaterialQueryRequest_PlanAirDate *, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest_PlanAirDate * SOAP_FMAC4 soap_get__ns1__MaterialQueryRequest_PlanAirDate(struct soap*, _ns1__MaterialQueryRequest_PlanAirDate *, const char*, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest_PlanAirDate * SOAP_FMAC4 soap_in__ns1__MaterialQueryRequest_PlanAirDate(struct soap*, const char*, _ns1__MaterialQueryRequest_PlanAirDate *, const char*);

#define soap_new__ns1__MaterialQueryRequest_PlanAirDate(soap, n) soap_instantiate__ns1__MaterialQueryRequest_PlanAirDate(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__MaterialQueryRequest_PlanAirDate(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__MaterialQueryRequest_PlanAirDate * SOAP_FMAC4 soap_instantiate__ns1__MaterialQueryRequest_PlanAirDate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__MaterialQueryRequest_PlanAirDate(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute
#define SOAP_TYPE__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute (43)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, const char*, int, const _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *, const char*);
SOAP_FMAC3 _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute * SOAP_FMAC4 soap_get__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute * SOAP_FMAC4 soap_in__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, const char*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *, const char*);

#define soap_new__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(soap, n) soap_instantiate__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute * SOAP_FMAC4 soap_instantiate__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ClipIsExistQueryResult
#define SOAP_TYPE__ns1__ClipIsExistQueryResult (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ClipIsExistQueryResult(struct soap*, const char*, int, const _ns1__ClipIsExistQueryResult *, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult * SOAP_FMAC4 soap_get__ns1__ClipIsExistQueryResult(struct soap*, _ns1__ClipIsExistQueryResult *, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult * SOAP_FMAC4 soap_in__ns1__ClipIsExistQueryResult(struct soap*, const char*, _ns1__ClipIsExistQueryResult *, const char*);

#define soap_new__ns1__ClipIsExistQueryResult(soap, n) soap_instantiate__ns1__ClipIsExistQueryResult(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ClipIsExistQueryResult(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ClipIsExistQueryResult * SOAP_FMAC4 soap_instantiate__ns1__ClipIsExistQueryResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ClipIsExistQueryResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__ClipExistQueryRequest
#define SOAP_TYPE__ns1__ClipExistQueryRequest (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ClipExistQueryRequest(struct soap*, const char*, int, const _ns1__ClipExistQueryRequest *, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest * SOAP_FMAC4 soap_get__ns1__ClipExistQueryRequest(struct soap*, _ns1__ClipExistQueryRequest *, const char*, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest * SOAP_FMAC4 soap_in__ns1__ClipExistQueryRequest(struct soap*, const char*, _ns1__ClipExistQueryRequest *, const char*);

#define soap_new__ns1__ClipExistQueryRequest(soap, n) soap_instantiate__ns1__ClipExistQueryRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ClipExistQueryRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ClipExistQueryRequest * SOAP_FMAC4 soap_instantiate__ns1__ClipExistQueryRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ClipExistQueryRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__MaterialQueryRequest
#define SOAP_TYPE__ns1__MaterialQueryRequest (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__MaterialQueryRequest(struct soap*, const char*, int, const _ns1__MaterialQueryRequest *, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest * SOAP_FMAC4 soap_get__ns1__MaterialQueryRequest(struct soap*, _ns1__MaterialQueryRequest *, const char*, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest * SOAP_FMAC4 soap_in__ns1__MaterialQueryRequest(struct soap*, const char*, _ns1__MaterialQueryRequest *, const char*);

#define soap_new__ns1__MaterialQueryRequest(soap, n) soap_instantiate__ns1__MaterialQueryRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__MaterialQueryRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__MaterialQueryRequest * SOAP_FMAC4 soap_instantiate__ns1__MaterialQueryRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__MaterialQueryRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__ProgramBasicEntityType
#define SOAP_TYPE_ns1__ProgramBasicEntityType (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ProgramBasicEntityType(struct soap*, const char*, int, const ns1__ProgramBasicEntityType *, const char*);
SOAP_FMAC3 ns1__ProgramBasicEntityType * SOAP_FMAC4 soap_get_ns1__ProgramBasicEntityType(struct soap*, ns1__ProgramBasicEntityType *, const char*, const char*);
SOAP_FMAC3 ns1__ProgramBasicEntityType * SOAP_FMAC4 soap_in_ns1__ProgramBasicEntityType(struct soap*, const char*, ns1__ProgramBasicEntityType *, const char*);

#define soap_new_ns1__ProgramBasicEntityType(soap, n) soap_instantiate_ns1__ProgramBasicEntityType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__ProgramBasicEntityType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns1__ProgramBasicEntityType * SOAP_FMAC4 soap_instantiate_ns1__ProgramBasicEntityType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ProgramBasicEntityType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__QueryCacheResponse
#define SOAP_TYPE__CLIPSVR__QueryCacheResponse (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__QueryCacheResponse(struct soap*, const char*, int, const _CLIPSVR__QueryCacheResponse *, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCacheResponse * SOAP_FMAC4 soap_get__CLIPSVR__QueryCacheResponse(struct soap*, _CLIPSVR__QueryCacheResponse *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCacheResponse * SOAP_FMAC4 soap_in__CLIPSVR__QueryCacheResponse(struct soap*, const char*, _CLIPSVR__QueryCacheResponse *, const char*);

#define soap_new__CLIPSVR__QueryCacheResponse(soap, n) soap_instantiate__CLIPSVR__QueryCacheResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__QueryCacheResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__QueryCacheResponse * SOAP_FMAC4 soap_instantiate__CLIPSVR__QueryCacheResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__QueryCacheResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__QueryCache
#define SOAP_TYPE__CLIPSVR__QueryCache (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__QueryCache(struct soap*, const char*, int, const _CLIPSVR__QueryCache *, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCache * SOAP_FMAC4 soap_get__CLIPSVR__QueryCache(struct soap*, _CLIPSVR__QueryCache *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCache * SOAP_FMAC4 soap_in__CLIPSVR__QueryCache(struct soap*, const char*, _CLIPSVR__QueryCache *, const char*);

#define soap_new__CLIPSVR__QueryCache(soap, n) soap_instantiate__CLIPSVR__QueryCache(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__QueryCache(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__QueryCache * SOAP_FMAC4 soap_instantiate__CLIPSVR__QueryCache(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__QueryCache(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__ClipIsExistQueryResponse
#define SOAP_TYPE__CLIPSVR__ClipIsExistQueryResponse (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__ClipIsExistQueryResponse(struct soap*, const char*, int, const _CLIPSVR__ClipIsExistQueryResponse *, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQueryResponse * SOAP_FMAC4 soap_get__CLIPSVR__ClipIsExistQueryResponse(struct soap*, _CLIPSVR__ClipIsExistQueryResponse *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQueryResponse * SOAP_FMAC4 soap_in__CLIPSVR__ClipIsExistQueryResponse(struct soap*, const char*, _CLIPSVR__ClipIsExistQueryResponse *, const char*);

#define soap_new__CLIPSVR__ClipIsExistQueryResponse(soap, n) soap_instantiate__CLIPSVR__ClipIsExistQueryResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__ClipIsExistQueryResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__ClipIsExistQueryResponse * SOAP_FMAC4 soap_instantiate__CLIPSVR__ClipIsExistQueryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__ClipIsExistQueryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__ClipIsExistQuery
#define SOAP_TYPE__CLIPSVR__ClipIsExistQuery (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__ClipIsExistQuery(struct soap*, const char*, int, const _CLIPSVR__ClipIsExistQuery *, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQuery * SOAP_FMAC4 soap_get__CLIPSVR__ClipIsExistQuery(struct soap*, _CLIPSVR__ClipIsExistQuery *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQuery * SOAP_FMAC4 soap_in__CLIPSVR__ClipIsExistQuery(struct soap*, const char*, _CLIPSVR__ClipIsExistQuery *, const char*);

#define soap_new__CLIPSVR__ClipIsExistQuery(soap, n) soap_instantiate__CLIPSVR__ClipIsExistQuery(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__ClipIsExistQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__ClipIsExistQuery * SOAP_FMAC4 soap_instantiate__CLIPSVR__ClipIsExistQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__ClipIsExistQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__MaterialQueryResponse
#define SOAP_TYPE__CLIPSVR__MaterialQueryResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__MaterialQueryResponse(struct soap*, const char*, int, const _CLIPSVR__MaterialQueryResponse *, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQueryResponse * SOAP_FMAC4 soap_get__CLIPSVR__MaterialQueryResponse(struct soap*, _CLIPSVR__MaterialQueryResponse *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQueryResponse * SOAP_FMAC4 soap_in__CLIPSVR__MaterialQueryResponse(struct soap*, const char*, _CLIPSVR__MaterialQueryResponse *, const char*);

#define soap_new__CLIPSVR__MaterialQueryResponse(soap, n) soap_instantiate__CLIPSVR__MaterialQueryResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__MaterialQueryResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__MaterialQueryResponse * SOAP_FMAC4 soap_instantiate__CLIPSVR__MaterialQueryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__MaterialQueryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__MaterialQuery
#define SOAP_TYPE__CLIPSVR__MaterialQuery (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__MaterialQuery(struct soap*, const char*, int, const _CLIPSVR__MaterialQuery *, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQuery * SOAP_FMAC4 soap_get__CLIPSVR__MaterialQuery(struct soap*, _CLIPSVR__MaterialQuery *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQuery * SOAP_FMAC4 soap_in__CLIPSVR__MaterialQuery(struct soap*, const char*, _CLIPSVR__MaterialQuery *, const char*);

#define soap_new__CLIPSVR__MaterialQuery(soap, n) soap_instantiate__CLIPSVR__MaterialQuery(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__MaterialQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__MaterialQuery * SOAP_FMAC4 soap_instantiate__CLIPSVR__MaterialQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__MaterialQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__TransferTaskExcuteResultNotifyResponse
#define SOAP_TYPE__CLIPSVR__TransferTaskExcuteResultNotifyResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, const char*, int, const _CLIPSVR__TransferTaskExcuteResultNotifyResponse *, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotifyResponse * SOAP_FMAC4 soap_get__CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotifyResponse * SOAP_FMAC4 soap_in__CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, const char*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse *, const char*);

#define soap_new__CLIPSVR__TransferTaskExcuteResultNotifyResponse(soap, n) soap_instantiate__CLIPSVR__TransferTaskExcuteResultNotifyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__TransferTaskExcuteResultNotifyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotifyResponse * SOAP_FMAC4 soap_instantiate__CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__TransferTaskExcuteResultNotify
#define SOAP_TYPE__CLIPSVR__TransferTaskExcuteResultNotify (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, const char*, int, const _CLIPSVR__TransferTaskExcuteResultNotify *, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_get__CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotify *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_in__CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, const char*, _CLIPSVR__TransferTaskExcuteResultNotify *, const char*);

#define soap_new__CLIPSVR__TransferTaskExcuteResultNotify(soap, n) soap_instantiate__CLIPSVR__TransferTaskExcuteResultNotify(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__TransferTaskExcuteResultNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_instantiate__CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__OutStorageFunctionResponse
#define SOAP_TYPE__CLIPSVR__OutStorageFunctionResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__OutStorageFunctionResponse(struct soap*, const char*, int, const _CLIPSVR__OutStorageFunctionResponse *, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunctionResponse * SOAP_FMAC4 soap_get__CLIPSVR__OutStorageFunctionResponse(struct soap*, _CLIPSVR__OutStorageFunctionResponse *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunctionResponse * SOAP_FMAC4 soap_in__CLIPSVR__OutStorageFunctionResponse(struct soap*, const char*, _CLIPSVR__OutStorageFunctionResponse *, const char*);

#define soap_new__CLIPSVR__OutStorageFunctionResponse(soap, n) soap_instantiate__CLIPSVR__OutStorageFunctionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__OutStorageFunctionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__OutStorageFunctionResponse * SOAP_FMAC4 soap_instantiate__CLIPSVR__OutStorageFunctionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__OutStorageFunctionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__CLIPSVR__OutStorageFunction
#define SOAP_TYPE__CLIPSVR__OutStorageFunction (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__CLIPSVR__OutStorageFunction(struct soap*, const char*, int, const _CLIPSVR__OutStorageFunction *, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunction * SOAP_FMAC4 soap_get__CLIPSVR__OutStorageFunction(struct soap*, _CLIPSVR__OutStorageFunction *, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunction * SOAP_FMAC4 soap_in__CLIPSVR__OutStorageFunction(struct soap*, const char*, _CLIPSVR__OutStorageFunction *, const char*);

#define soap_new__CLIPSVR__OutStorageFunction(soap, n) soap_instantiate__CLIPSVR__OutStorageFunction(soap, n, NULL, NULL, NULL)


#define soap_delete__CLIPSVR__OutStorageFunction(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _CLIPSVR__OutStorageFunction * SOAP_FMAC4 soap_instantiate__CLIPSVR__OutStorageFunction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__CLIPSVR__OutStorageFunction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__ArrayOfProgramBasicEntityType
#define SOAP_TYPE_CLIPSVR__ArrayOfProgramBasicEntityType (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, const char*, int, const CLIPSVR__ArrayOfProgramBasicEntityType *, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfProgramBasicEntityType * SOAP_FMAC4 soap_get_CLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, CLIPSVR__ArrayOfProgramBasicEntityType *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfProgramBasicEntityType * SOAP_FMAC4 soap_in_CLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, const char*, CLIPSVR__ArrayOfProgramBasicEntityType *, const char*);

#define soap_new_CLIPSVR__ArrayOfProgramBasicEntityType(soap, n) soap_instantiate_CLIPSVR__ArrayOfProgramBasicEntityType(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__ArrayOfProgramBasicEntityType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__ArrayOfProgramBasicEntityType * SOAP_FMAC4 soap_instantiate_CLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__StatusDesc
#define SOAP_TYPE_CLIPSVR__StatusDesc (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__StatusDesc(struct soap*, const char*, int, const CLIPSVR__StatusDesc *, const char*);
SOAP_FMAC3 CLIPSVR__StatusDesc * SOAP_FMAC4 soap_get_CLIPSVR__StatusDesc(struct soap*, CLIPSVR__StatusDesc *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__StatusDesc * SOAP_FMAC4 soap_in_CLIPSVR__StatusDesc(struct soap*, const char*, CLIPSVR__StatusDesc *, const char*);

#define soap_new_CLIPSVR__StatusDesc(soap, n) soap_instantiate_CLIPSVR__StatusDesc(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__StatusDesc(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__StatusDesc * SOAP_FMAC4 soap_instantiate_CLIPSVR__StatusDesc(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__StatusDesc(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute
#define SOAP_TYPE_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, const char*, int, const CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute * SOAP_FMAC4 soap_get_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute * SOAP_FMAC4 soap_in_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, const char*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *, const char*);

#define soap_new_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(soap, n) soap_instantiate_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute * SOAP_FMAC4 soap_instantiate_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__BreakPoint
#define SOAP_TYPE_CLIPSVR__BreakPoint (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__BreakPoint(struct soap*, const char*, int, const CLIPSVR__BreakPoint *, const char*);
SOAP_FMAC3 CLIPSVR__BreakPoint * SOAP_FMAC4 soap_get_CLIPSVR__BreakPoint(struct soap*, CLIPSVR__BreakPoint *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__BreakPoint * SOAP_FMAC4 soap_in_CLIPSVR__BreakPoint(struct soap*, const char*, CLIPSVR__BreakPoint *, const char*);

#define soap_new_CLIPSVR__BreakPoint(soap, n) soap_instantiate_CLIPSVR__BreakPoint(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__BreakPoint(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__BreakPoint * SOAP_FMAC4 soap_instantiate_CLIPSVR__BreakPoint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__BreakPoint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__ArrayOfBreakPoint
#define SOAP_TYPE_CLIPSVR__ArrayOfBreakPoint (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__ArrayOfBreakPoint(struct soap*, const char*, int, const CLIPSVR__ArrayOfBreakPoint *, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfBreakPoint * SOAP_FMAC4 soap_get_CLIPSVR__ArrayOfBreakPoint(struct soap*, CLIPSVR__ArrayOfBreakPoint *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfBreakPoint * SOAP_FMAC4 soap_in_CLIPSVR__ArrayOfBreakPoint(struct soap*, const char*, CLIPSVR__ArrayOfBreakPoint *, const char*);

#define soap_new_CLIPSVR__ArrayOfBreakPoint(soap, n) soap_instantiate_CLIPSVR__ArrayOfBreakPoint(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__ArrayOfBreakPoint(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__ArrayOfBreakPoint * SOAP_FMAC4 soap_instantiate_CLIPSVR__ArrayOfBreakPoint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__ArrayOfBreakPoint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__OutMessageFile
#define SOAP_TYPE_CLIPSVR__OutMessageFile (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__OutMessageFile(struct soap*, const char*, int, const CLIPSVR__OutMessageFile *, const char*);
SOAP_FMAC3 CLIPSVR__OutMessageFile * SOAP_FMAC4 soap_get_CLIPSVR__OutMessageFile(struct soap*, CLIPSVR__OutMessageFile *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__OutMessageFile * SOAP_FMAC4 soap_in_CLIPSVR__OutMessageFile(struct soap*, const char*, CLIPSVR__OutMessageFile *, const char*);

#define soap_new_CLIPSVR__OutMessageFile(soap, n) soap_instantiate_CLIPSVR__OutMessageFile(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__OutMessageFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__OutMessageFile * SOAP_FMAC4 soap_instantiate_CLIPSVR__OutMessageFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__OutMessageFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__ArrayOfOutMessageFile
#define SOAP_TYPE_CLIPSVR__ArrayOfOutMessageFile (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__ArrayOfOutMessageFile(struct soap*, const char*, int, const CLIPSVR__ArrayOfOutMessageFile *, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfOutMessageFile * SOAP_FMAC4 soap_get_CLIPSVR__ArrayOfOutMessageFile(struct soap*, CLIPSVR__ArrayOfOutMessageFile *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfOutMessageFile * SOAP_FMAC4 soap_in_CLIPSVR__ArrayOfOutMessageFile(struct soap*, const char*, CLIPSVR__ArrayOfOutMessageFile *, const char*);

#define soap_new_CLIPSVR__ArrayOfOutMessageFile(soap, n) soap_instantiate_CLIPSVR__ArrayOfOutMessageFile(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__ArrayOfOutMessageFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__ArrayOfOutMessageFile * SOAP_FMAC4 soap_instantiate_CLIPSVR__ArrayOfOutMessageFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__ArrayOfOutMessageFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_CLIPSVR__OutMessage
#define SOAP_TYPE_CLIPSVR__OutMessage (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_CLIPSVR__OutMessage(struct soap*, const char*, int, const CLIPSVR__OutMessage *, const char*);
SOAP_FMAC3 CLIPSVR__OutMessage * SOAP_FMAC4 soap_get_CLIPSVR__OutMessage(struct soap*, CLIPSVR__OutMessage *, const char*, const char*);
SOAP_FMAC3 CLIPSVR__OutMessage * SOAP_FMAC4 soap_in_CLIPSVR__OutMessage(struct soap*, const char*, CLIPSVR__OutMessage *, const char*);

#define soap_new_CLIPSVR__OutMessage(soap, n) soap_instantiate_CLIPSVR__OutMessage(soap, n, NULL, NULL, NULL)


#define soap_delete_CLIPSVR__OutMessage(soap, p) soap_delete(soap, p)

SOAP_FMAC3 CLIPSVR__OutMessage * SOAP_FMAC4 soap_instantiate_CLIPSVR__OutMessage(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_CLIPSVR__OutMessage(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___CLIPSVR3__QueryCache
#define SOAP_TYPE___CLIPSVR3__QueryCache (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR3__QueryCache(struct soap*, struct __CLIPSVR3__QueryCache *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR3__QueryCache(struct soap*, const struct __CLIPSVR3__QueryCache *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR3__QueryCache(struct soap*, const struct __CLIPSVR3__QueryCache *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR3__QueryCache(struct soap*, const char*, int, const struct __CLIPSVR3__QueryCache *, const char*);
SOAP_FMAC3 struct __CLIPSVR3__QueryCache * SOAP_FMAC4 soap_get___CLIPSVR3__QueryCache(struct soap*, struct __CLIPSVR3__QueryCache *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR3__QueryCache * SOAP_FMAC4 soap_in___CLIPSVR3__QueryCache(struct soap*, const char*, struct __CLIPSVR3__QueryCache *, const char*);

#define soap_new___CLIPSVR3__QueryCache(soap, n) soap_instantiate___CLIPSVR3__QueryCache(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR3__QueryCache(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR3__QueryCache * SOAP_FMAC4 soap_instantiate___CLIPSVR3__QueryCache(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR3__QueryCache(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR3__ClipIsExistQuery
#define SOAP_TYPE___CLIPSVR3__ClipIsExistQuery (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR3__ClipIsExistQuery(struct soap*, struct __CLIPSVR3__ClipIsExistQuery *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR3__ClipIsExistQuery(struct soap*, const struct __CLIPSVR3__ClipIsExistQuery *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR3__ClipIsExistQuery(struct soap*, const struct __CLIPSVR3__ClipIsExistQuery *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR3__ClipIsExistQuery(struct soap*, const char*, int, const struct __CLIPSVR3__ClipIsExistQuery *, const char*);
SOAP_FMAC3 struct __CLIPSVR3__ClipIsExistQuery * SOAP_FMAC4 soap_get___CLIPSVR3__ClipIsExistQuery(struct soap*, struct __CLIPSVR3__ClipIsExistQuery *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR3__ClipIsExistQuery * SOAP_FMAC4 soap_in___CLIPSVR3__ClipIsExistQuery(struct soap*, const char*, struct __CLIPSVR3__ClipIsExistQuery *, const char*);

#define soap_new___CLIPSVR3__ClipIsExistQuery(soap, n) soap_instantiate___CLIPSVR3__ClipIsExistQuery(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR3__ClipIsExistQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR3__ClipIsExistQuery * SOAP_FMAC4 soap_instantiate___CLIPSVR3__ClipIsExistQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR3__ClipIsExistQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR3__MaterialQuery
#define SOAP_TYPE___CLIPSVR3__MaterialQuery (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR3__MaterialQuery(struct soap*, struct __CLIPSVR3__MaterialQuery *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR3__MaterialQuery(struct soap*, const struct __CLIPSVR3__MaterialQuery *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR3__MaterialQuery(struct soap*, const struct __CLIPSVR3__MaterialQuery *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR3__MaterialQuery(struct soap*, const char*, int, const struct __CLIPSVR3__MaterialQuery *, const char*);
SOAP_FMAC3 struct __CLIPSVR3__MaterialQuery * SOAP_FMAC4 soap_get___CLIPSVR3__MaterialQuery(struct soap*, struct __CLIPSVR3__MaterialQuery *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR3__MaterialQuery * SOAP_FMAC4 soap_in___CLIPSVR3__MaterialQuery(struct soap*, const char*, struct __CLIPSVR3__MaterialQuery *, const char*);

#define soap_new___CLIPSVR3__MaterialQuery(soap, n) soap_instantiate___CLIPSVR3__MaterialQuery(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR3__MaterialQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR3__MaterialQuery * SOAP_FMAC4 soap_instantiate___CLIPSVR3__MaterialQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR3__MaterialQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR3__TransferTaskExcuteResultNotify
#define SOAP_TYPE___CLIPSVR3__TransferTaskExcuteResultNotify (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, struct __CLIPSVR3__TransferTaskExcuteResultNotify *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, const struct __CLIPSVR3__TransferTaskExcuteResultNotify *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, const struct __CLIPSVR3__TransferTaskExcuteResultNotify *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, const char*, int, const struct __CLIPSVR3__TransferTaskExcuteResultNotify *, const char*);
SOAP_FMAC3 struct __CLIPSVR3__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_get___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, struct __CLIPSVR3__TransferTaskExcuteResultNotify *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR3__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_in___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, const char*, struct __CLIPSVR3__TransferTaskExcuteResultNotify *, const char*);

#define soap_new___CLIPSVR3__TransferTaskExcuteResultNotify(soap, n) soap_instantiate___CLIPSVR3__TransferTaskExcuteResultNotify(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR3__TransferTaskExcuteResultNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR3__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_instantiate___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR3__TransferTaskExcuteResultNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR3__OutStorageFunction
#define SOAP_TYPE___CLIPSVR3__OutStorageFunction (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR3__OutStorageFunction(struct soap*, struct __CLIPSVR3__OutStorageFunction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR3__OutStorageFunction(struct soap*, const struct __CLIPSVR3__OutStorageFunction *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR3__OutStorageFunction(struct soap*, const struct __CLIPSVR3__OutStorageFunction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR3__OutStorageFunction(struct soap*, const char*, int, const struct __CLIPSVR3__OutStorageFunction *, const char*);
SOAP_FMAC3 struct __CLIPSVR3__OutStorageFunction * SOAP_FMAC4 soap_get___CLIPSVR3__OutStorageFunction(struct soap*, struct __CLIPSVR3__OutStorageFunction *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR3__OutStorageFunction * SOAP_FMAC4 soap_in___CLIPSVR3__OutStorageFunction(struct soap*, const char*, struct __CLIPSVR3__OutStorageFunction *, const char*);

#define soap_new___CLIPSVR3__OutStorageFunction(soap, n) soap_instantiate___CLIPSVR3__OutStorageFunction(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR3__OutStorageFunction(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR3__OutStorageFunction * SOAP_FMAC4 soap_instantiate___CLIPSVR3__OutStorageFunction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR3__OutStorageFunction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR2__QueryCache
#define SOAP_TYPE___CLIPSVR2__QueryCache (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR2__QueryCache(struct soap*, struct __CLIPSVR2__QueryCache *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR2__QueryCache(struct soap*, const struct __CLIPSVR2__QueryCache *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR2__QueryCache(struct soap*, const struct __CLIPSVR2__QueryCache *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR2__QueryCache(struct soap*, const char*, int, const struct __CLIPSVR2__QueryCache *, const char*);
SOAP_FMAC3 struct __CLIPSVR2__QueryCache * SOAP_FMAC4 soap_get___CLIPSVR2__QueryCache(struct soap*, struct __CLIPSVR2__QueryCache *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR2__QueryCache * SOAP_FMAC4 soap_in___CLIPSVR2__QueryCache(struct soap*, const char*, struct __CLIPSVR2__QueryCache *, const char*);

#define soap_new___CLIPSVR2__QueryCache(soap, n) soap_instantiate___CLIPSVR2__QueryCache(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR2__QueryCache(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR2__QueryCache * SOAP_FMAC4 soap_instantiate___CLIPSVR2__QueryCache(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR2__QueryCache(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR2__ClipIsExistQuery
#define SOAP_TYPE___CLIPSVR2__ClipIsExistQuery (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR2__ClipIsExistQuery(struct soap*, struct __CLIPSVR2__ClipIsExistQuery *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR2__ClipIsExistQuery(struct soap*, const struct __CLIPSVR2__ClipIsExistQuery *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR2__ClipIsExistQuery(struct soap*, const struct __CLIPSVR2__ClipIsExistQuery *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR2__ClipIsExistQuery(struct soap*, const char*, int, const struct __CLIPSVR2__ClipIsExistQuery *, const char*);
SOAP_FMAC3 struct __CLIPSVR2__ClipIsExistQuery * SOAP_FMAC4 soap_get___CLIPSVR2__ClipIsExistQuery(struct soap*, struct __CLIPSVR2__ClipIsExistQuery *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR2__ClipIsExistQuery * SOAP_FMAC4 soap_in___CLIPSVR2__ClipIsExistQuery(struct soap*, const char*, struct __CLIPSVR2__ClipIsExistQuery *, const char*);

#define soap_new___CLIPSVR2__ClipIsExistQuery(soap, n) soap_instantiate___CLIPSVR2__ClipIsExistQuery(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR2__ClipIsExistQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR2__ClipIsExistQuery * SOAP_FMAC4 soap_instantiate___CLIPSVR2__ClipIsExistQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR2__ClipIsExistQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR2__MaterialQuery
#define SOAP_TYPE___CLIPSVR2__MaterialQuery (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR2__MaterialQuery(struct soap*, struct __CLIPSVR2__MaterialQuery *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR2__MaterialQuery(struct soap*, const struct __CLIPSVR2__MaterialQuery *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR2__MaterialQuery(struct soap*, const struct __CLIPSVR2__MaterialQuery *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR2__MaterialQuery(struct soap*, const char*, int, const struct __CLIPSVR2__MaterialQuery *, const char*);
SOAP_FMAC3 struct __CLIPSVR2__MaterialQuery * SOAP_FMAC4 soap_get___CLIPSVR2__MaterialQuery(struct soap*, struct __CLIPSVR2__MaterialQuery *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR2__MaterialQuery * SOAP_FMAC4 soap_in___CLIPSVR2__MaterialQuery(struct soap*, const char*, struct __CLIPSVR2__MaterialQuery *, const char*);

#define soap_new___CLIPSVR2__MaterialQuery(soap, n) soap_instantiate___CLIPSVR2__MaterialQuery(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR2__MaterialQuery(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR2__MaterialQuery * SOAP_FMAC4 soap_instantiate___CLIPSVR2__MaterialQuery(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR2__MaterialQuery(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR2__TransferTaskExcuteResultNotify
#define SOAP_TYPE___CLIPSVR2__TransferTaskExcuteResultNotify (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, struct __CLIPSVR2__TransferTaskExcuteResultNotify *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, const struct __CLIPSVR2__TransferTaskExcuteResultNotify *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, const struct __CLIPSVR2__TransferTaskExcuteResultNotify *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, const char*, int, const struct __CLIPSVR2__TransferTaskExcuteResultNotify *, const char*);
SOAP_FMAC3 struct __CLIPSVR2__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_get___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, struct __CLIPSVR2__TransferTaskExcuteResultNotify *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR2__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_in___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, const char*, struct __CLIPSVR2__TransferTaskExcuteResultNotify *, const char*);

#define soap_new___CLIPSVR2__TransferTaskExcuteResultNotify(soap, n) soap_instantiate___CLIPSVR2__TransferTaskExcuteResultNotify(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR2__TransferTaskExcuteResultNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR2__TransferTaskExcuteResultNotify * SOAP_FMAC4 soap_instantiate___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR2__TransferTaskExcuteResultNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___CLIPSVR2__OutStorageFunction
#define SOAP_TYPE___CLIPSVR2__OutStorageFunction (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___CLIPSVR2__OutStorageFunction(struct soap*, struct __CLIPSVR2__OutStorageFunction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___CLIPSVR2__OutStorageFunction(struct soap*, const struct __CLIPSVR2__OutStorageFunction *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___CLIPSVR2__OutStorageFunction(struct soap*, const struct __CLIPSVR2__OutStorageFunction *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___CLIPSVR2__OutStorageFunction(struct soap*, const char*, int, const struct __CLIPSVR2__OutStorageFunction *, const char*);
SOAP_FMAC3 struct __CLIPSVR2__OutStorageFunction * SOAP_FMAC4 soap_get___CLIPSVR2__OutStorageFunction(struct soap*, struct __CLIPSVR2__OutStorageFunction *, const char*, const char*);
SOAP_FMAC3 struct __CLIPSVR2__OutStorageFunction * SOAP_FMAC4 soap_in___CLIPSVR2__OutStorageFunction(struct soap*, const char*, struct __CLIPSVR2__OutStorageFunction *, const char*);

#define soap_new___CLIPSVR2__OutStorageFunction(soap, n) soap_instantiate___CLIPSVR2__OutStorageFunction(soap, n, NULL, NULL, NULL)


#define soap_delete___CLIPSVR2__OutStorageFunction(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __CLIPSVR2__OutStorageFunction * SOAP_FMAC4 soap_instantiate___CLIPSVR2__OutStorageFunction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___CLIPSVR2__OutStorageFunction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__QueryCacheResponse
#define SOAP_TYPE_PointerTo_CLIPSVR__QueryCacheResponse (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__QueryCacheResponse(struct soap*, _CLIPSVR__QueryCacheResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__QueryCacheResponse(struct soap*, _CLIPSVR__QueryCacheResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__QueryCacheResponse(struct soap*, const char *, int, _CLIPSVR__QueryCacheResponse *const*, const char *);
SOAP_FMAC3 _CLIPSVR__QueryCacheResponse ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__QueryCacheResponse(struct soap*, _CLIPSVR__QueryCacheResponse **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCacheResponse ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__QueryCacheResponse(struct soap*, const char*, _CLIPSVR__QueryCacheResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__QueryCache
#define SOAP_TYPE_PointerTo_CLIPSVR__QueryCache (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__QueryCache(struct soap*, _CLIPSVR__QueryCache *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__QueryCache(struct soap*, _CLIPSVR__QueryCache *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__QueryCache(struct soap*, const char *, int, _CLIPSVR__QueryCache *const*, const char *);
SOAP_FMAC3 _CLIPSVR__QueryCache ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__QueryCache(struct soap*, _CLIPSVR__QueryCache **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__QueryCache ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__QueryCache(struct soap*, const char*, _CLIPSVR__QueryCache **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__ClipIsExistQueryResponse
#define SOAP_TYPE_PointerTo_CLIPSVR__ClipIsExistQueryResponse (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__ClipIsExistQueryResponse(struct soap*, _CLIPSVR__ClipIsExistQueryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__ClipIsExistQueryResponse(struct soap*, _CLIPSVR__ClipIsExistQueryResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__ClipIsExistQueryResponse(struct soap*, const char *, int, _CLIPSVR__ClipIsExistQueryResponse *const*, const char *);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQueryResponse ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__ClipIsExistQueryResponse(struct soap*, _CLIPSVR__ClipIsExistQueryResponse **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQueryResponse ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__ClipIsExistQueryResponse(struct soap*, const char*, _CLIPSVR__ClipIsExistQueryResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__ClipIsExistQuery
#define SOAP_TYPE_PointerTo_CLIPSVR__ClipIsExistQuery (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__ClipIsExistQuery(struct soap*, _CLIPSVR__ClipIsExistQuery *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__ClipIsExistQuery(struct soap*, _CLIPSVR__ClipIsExistQuery *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__ClipIsExistQuery(struct soap*, const char *, int, _CLIPSVR__ClipIsExistQuery *const*, const char *);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQuery ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__ClipIsExistQuery(struct soap*, _CLIPSVR__ClipIsExistQuery **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ClipIsExistQuery ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__ClipIsExistQuery(struct soap*, const char*, _CLIPSVR__ClipIsExistQuery **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__MaterialQueryResponse
#define SOAP_TYPE_PointerTo_CLIPSVR__MaterialQueryResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__MaterialQueryResponse(struct soap*, _CLIPSVR__MaterialQueryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__MaterialQueryResponse(struct soap*, _CLIPSVR__MaterialQueryResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__MaterialQueryResponse(struct soap*, const char *, int, _CLIPSVR__MaterialQueryResponse *const*, const char *);
SOAP_FMAC3 _CLIPSVR__MaterialQueryResponse ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__MaterialQueryResponse(struct soap*, _CLIPSVR__MaterialQueryResponse **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQueryResponse ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__MaterialQueryResponse(struct soap*, const char*, _CLIPSVR__MaterialQueryResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__MaterialQuery
#define SOAP_TYPE_PointerTo_CLIPSVR__MaterialQuery (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__MaterialQuery(struct soap*, _CLIPSVR__MaterialQuery *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__MaterialQuery(struct soap*, _CLIPSVR__MaterialQuery *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__MaterialQuery(struct soap*, const char *, int, _CLIPSVR__MaterialQuery *const*, const char *);
SOAP_FMAC3 _CLIPSVR__MaterialQuery ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__MaterialQuery(struct soap*, _CLIPSVR__MaterialQuery **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__MaterialQuery ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__MaterialQuery(struct soap*, const char*, _CLIPSVR__MaterialQuery **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse
#define SOAP_TYPE_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, const char *, int, _CLIPSVR__TransferTaskExcuteResultNotifyResponse *const*, const char *);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotifyResponse ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotifyResponse ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__TransferTaskExcuteResultNotifyResponse(struct soap*, const char*, _CLIPSVR__TransferTaskExcuteResultNotifyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify
#define SOAP_TYPE_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotify *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotify *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, const char *, int, _CLIPSVR__TransferTaskExcuteResultNotify *const*, const char *);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotify ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, _CLIPSVR__TransferTaskExcuteResultNotify **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__TransferTaskExcuteResultNotify ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__TransferTaskExcuteResultNotify(struct soap*, const char*, _CLIPSVR__TransferTaskExcuteResultNotify **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__OutStorageFunctionResponse
#define SOAP_TYPE_PointerTo_CLIPSVR__OutStorageFunctionResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__OutStorageFunctionResponse(struct soap*, _CLIPSVR__OutStorageFunctionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__OutStorageFunctionResponse(struct soap*, _CLIPSVR__OutStorageFunctionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__OutStorageFunctionResponse(struct soap*, const char *, int, _CLIPSVR__OutStorageFunctionResponse *const*, const char *);
SOAP_FMAC3 _CLIPSVR__OutStorageFunctionResponse ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__OutStorageFunctionResponse(struct soap*, _CLIPSVR__OutStorageFunctionResponse **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunctionResponse ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__OutStorageFunctionResponse(struct soap*, const char*, _CLIPSVR__OutStorageFunctionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__OutStorageFunction
#define SOAP_TYPE_PointerTo_CLIPSVR__OutStorageFunction (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__OutStorageFunction(struct soap*, _CLIPSVR__OutStorageFunction *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__OutStorageFunction(struct soap*, _CLIPSVR__OutStorageFunction *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__OutStorageFunction(struct soap*, const char *, int, _CLIPSVR__OutStorageFunction *const*, const char *);
SOAP_FMAC3 _CLIPSVR__OutStorageFunction ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__OutStorageFunction(struct soap*, _CLIPSVR__OutStorageFunction **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__OutStorageFunction ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__OutStorageFunction(struct soap*, const char*, _CLIPSVR__OutStorageFunction **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult
#define SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, const char *, int, _ns1__ClipIsExistQueryResult_ClipArrayResult *const*, const char *);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult ** SOAP_FMAC4 soap_get_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult **, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult ** SOAP_FMAC4 soap_in_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult(struct soap*, const char*, _ns1__ClipIsExistQueryResult_ClipArrayResult **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem
#define SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, const char *, int, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem *const*, const char *);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem ** SOAP_FMAC4 soap_get_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem **, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem ** SOAP_FMAC4 soap_in_PointerTo_ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem(struct soap*, const char*, _ns1__ClipIsExistQueryResult_ClipArrayResult_ClipItem **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ClipExistQueryRequest_ClipArray
#define SOAP_TYPE_PointerTo_ns1__ClipExistQueryRequest_ClipArray (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ClipExistQueryRequest_ClipArray(struct soap*, _ns1__ClipExistQueryRequest_ClipArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ClipExistQueryRequest_ClipArray(struct soap*, _ns1__ClipExistQueryRequest_ClipArray *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ClipExistQueryRequest_ClipArray(struct soap*, const char *, int, _ns1__ClipExistQueryRequest_ClipArray *const*, const char *);
SOAP_FMAC3 _ns1__ClipExistQueryRequest_ClipArray ** SOAP_FMAC4 soap_get_PointerTo_ns1__ClipExistQueryRequest_ClipArray(struct soap*, _ns1__ClipExistQueryRequest_ClipArray **, const char*, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest_ClipArray ** SOAP_FMAC4 soap_in_PointerTo_ns1__ClipExistQueryRequest_ClipArray(struct soap*, const char*, _ns1__ClipExistQueryRequest_ClipArray **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__MaterialQueryRequest_PlanAirDate
#define SOAP_TYPE_PointerTo_ns1__MaterialQueryRequest_PlanAirDate (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__MaterialQueryRequest_PlanAirDate(struct soap*, _ns1__MaterialQueryRequest_PlanAirDate *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__MaterialQueryRequest_PlanAirDate(struct soap*, _ns1__MaterialQueryRequest_PlanAirDate *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__MaterialQueryRequest_PlanAirDate(struct soap*, const char *, int, _ns1__MaterialQueryRequest_PlanAirDate *const*, const char *);
SOAP_FMAC3 _ns1__MaterialQueryRequest_PlanAirDate ** SOAP_FMAC4 soap_get_PointerTo_ns1__MaterialQueryRequest_PlanAirDate(struct soap*, _ns1__MaterialQueryRequest_PlanAirDate **, const char*, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest_PlanAirDate ** SOAP_FMAC4 soap_in_PointerTo_ns1__MaterialQueryRequest_PlanAirDate(struct soap*, const char*, _ns1__MaterialQueryRequest_PlanAirDate **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult
#define SOAP_TYPE_PointerTo_ns1__ClipIsExistQueryResult (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ClipIsExistQueryResult(struct soap*, _ns1__ClipIsExistQueryResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ClipIsExistQueryResult(struct soap*, _ns1__ClipIsExistQueryResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ClipIsExistQueryResult(struct soap*, const char *, int, _ns1__ClipIsExistQueryResult *const*, const char *);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult ** SOAP_FMAC4 soap_get_PointerTo_ns1__ClipIsExistQueryResult(struct soap*, _ns1__ClipIsExistQueryResult **, const char*, const char*);
SOAP_FMAC3 _ns1__ClipIsExistQueryResult ** SOAP_FMAC4 soap_in_PointerTo_ns1__ClipIsExistQueryResult(struct soap*, const char*, _ns1__ClipIsExistQueryResult **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__ClipExistQueryRequest
#define SOAP_TYPE_PointerTo_ns1__ClipExistQueryRequest (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ClipExistQueryRequest(struct soap*, _ns1__ClipExistQueryRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ClipExistQueryRequest(struct soap*, _ns1__ClipExistQueryRequest *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ClipExistQueryRequest(struct soap*, const char *, int, _ns1__ClipExistQueryRequest *const*, const char *);
SOAP_FMAC3 _ns1__ClipExistQueryRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__ClipExistQueryRequest(struct soap*, _ns1__ClipExistQueryRequest **, const char*, const char*);
SOAP_FMAC3 _ns1__ClipExistQueryRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__ClipExistQueryRequest(struct soap*, const char*, _ns1__ClipExistQueryRequest **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__ArrayOfProgramBasicEntityType
#define SOAP_TYPE_PointerToCLIPSVR__ArrayOfProgramBasicEntityType (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, CLIPSVR__ArrayOfProgramBasicEntityType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, CLIPSVR__ArrayOfProgramBasicEntityType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, const char *, int, CLIPSVR__ArrayOfProgramBasicEntityType *const*, const char *);
SOAP_FMAC3 CLIPSVR__ArrayOfProgramBasicEntityType ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, CLIPSVR__ArrayOfProgramBasicEntityType **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfProgramBasicEntityType ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__ArrayOfProgramBasicEntityType(struct soap*, const char*, CLIPSVR__ArrayOfProgramBasicEntityType **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__MaterialQueryRequest
#define SOAP_TYPE_PointerTo_ns1__MaterialQueryRequest (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__MaterialQueryRequest(struct soap*, _ns1__MaterialQueryRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__MaterialQueryRequest(struct soap*, _ns1__MaterialQueryRequest *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__MaterialQueryRequest(struct soap*, const char *, int, _ns1__MaterialQueryRequest *const*, const char *);
SOAP_FMAC3 _ns1__MaterialQueryRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__MaterialQueryRequest(struct soap*, _ns1__MaterialQueryRequest **, const char*, const char*);
SOAP_FMAC3 _ns1__MaterialQueryRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__MaterialQueryRequest(struct soap*, const char*, _ns1__MaterialQueryRequest **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__StatusDesc
#define SOAP_TYPE_PointerToCLIPSVR__StatusDesc (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__StatusDesc(struct soap*, CLIPSVR__StatusDesc *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__StatusDesc(struct soap*, CLIPSVR__StatusDesc *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__StatusDesc(struct soap*, const char *, int, CLIPSVR__StatusDesc *const*, const char *);
SOAP_FMAC3 CLIPSVR__StatusDesc ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__StatusDesc(struct soap*, CLIPSVR__StatusDesc **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__StatusDesc ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__StatusDesc(struct soap*, const char*, CLIPSVR__StatusDesc **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__OutMessage
#define SOAP_TYPE_PointerToCLIPSVR__OutMessage (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__OutMessage(struct soap*, CLIPSVR__OutMessage *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__OutMessage(struct soap*, CLIPSVR__OutMessage *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__OutMessage(struct soap*, const char *, int, CLIPSVR__OutMessage *const*, const char *);
SOAP_FMAC3 CLIPSVR__OutMessage ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__OutMessage(struct soap*, CLIPSVR__OutMessage **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__OutMessage ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__OutMessage(struct soap*, const char*, CLIPSVR__OutMessage **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ProgramBasicEntityType
#define SOAP_TYPE_PointerTons1__ProgramBasicEntityType (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ProgramBasicEntityType(struct soap*, ns1__ProgramBasicEntityType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ProgramBasicEntityType(struct soap*, ns1__ProgramBasicEntityType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ProgramBasicEntityType(struct soap*, const char *, int, ns1__ProgramBasicEntityType *const*, const char *);
SOAP_FMAC3 ns1__ProgramBasicEntityType ** SOAP_FMAC4 soap_get_PointerTons1__ProgramBasicEntityType(struct soap*, ns1__ProgramBasicEntityType **, const char*, const char*);
SOAP_FMAC3 ns1__ProgramBasicEntityType ** SOAP_FMAC4 soap_in_PointerTons1__ProgramBasicEntityType(struct soap*, const char*, ns1__ProgramBasicEntityType **, const char*);

#ifndef SOAP_TYPE_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute
#define SOAP_TYPE_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, const char *, int, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute *const*, const char *);
SOAP_FMAC3 _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute ** SOAP_FMAC4 soap_get_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute **, const char*, const char*);
SOAP_FMAC3 _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute ** SOAP_FMAC4 soap_in_PointerTo_CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute(struct soap*, const char*, _CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute_ExtentionAttribute **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__BreakPoint
#define SOAP_TYPE_PointerToCLIPSVR__BreakPoint (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__BreakPoint(struct soap*, CLIPSVR__BreakPoint *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__BreakPoint(struct soap*, CLIPSVR__BreakPoint *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__BreakPoint(struct soap*, const char *, int, CLIPSVR__BreakPoint *const*, const char *);
SOAP_FMAC3 CLIPSVR__BreakPoint ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__BreakPoint(struct soap*, CLIPSVR__BreakPoint **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__BreakPoint ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__BreakPoint(struct soap*, const char*, CLIPSVR__BreakPoint **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__OutMessageFile
#define SOAP_TYPE_PointerToCLIPSVR__OutMessageFile (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__OutMessageFile(struct soap*, CLIPSVR__OutMessageFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__OutMessageFile(struct soap*, CLIPSVR__OutMessageFile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__OutMessageFile(struct soap*, const char *, int, CLIPSVR__OutMessageFile *const*, const char *);
SOAP_FMAC3 CLIPSVR__OutMessageFile ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__OutMessageFile(struct soap*, CLIPSVR__OutMessageFile **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__OutMessageFile ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__OutMessageFile(struct soap*, const char*, CLIPSVR__OutMessageFile **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute
#define SOAP_TYPE_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, const char *, int, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute *const*, const char *);
SOAP_FMAC3 CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute(struct soap*, const char*, CLIPSVR__ArrayOfExtentionAttributeTypeExtentionAttribute **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__ArrayOfBreakPoint
#define SOAP_TYPE_PointerToCLIPSVR__ArrayOfBreakPoint (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__ArrayOfBreakPoint(struct soap*, CLIPSVR__ArrayOfBreakPoint *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__ArrayOfBreakPoint(struct soap*, CLIPSVR__ArrayOfBreakPoint *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__ArrayOfBreakPoint(struct soap*, const char *, int, CLIPSVR__ArrayOfBreakPoint *const*, const char *);
SOAP_FMAC3 CLIPSVR__ArrayOfBreakPoint ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__ArrayOfBreakPoint(struct soap*, CLIPSVR__ArrayOfBreakPoint **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfBreakPoint ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__ArrayOfBreakPoint(struct soap*, const char*, CLIPSVR__ArrayOfBreakPoint **, const char*);

#ifndef SOAP_TYPE_PointerToCLIPSVR__ArrayOfOutMessageFile
#define SOAP_TYPE_PointerToCLIPSVR__ArrayOfOutMessageFile (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCLIPSVR__ArrayOfOutMessageFile(struct soap*, CLIPSVR__ArrayOfOutMessageFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCLIPSVR__ArrayOfOutMessageFile(struct soap*, CLIPSVR__ArrayOfOutMessageFile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCLIPSVR__ArrayOfOutMessageFile(struct soap*, const char *, int, CLIPSVR__ArrayOfOutMessageFile *const*, const char *);
SOAP_FMAC3 CLIPSVR__ArrayOfOutMessageFile ** SOAP_FMAC4 soap_get_PointerToCLIPSVR__ArrayOfOutMessageFile(struct soap*, CLIPSVR__ArrayOfOutMessageFile **, const char*, const char*);
SOAP_FMAC3 CLIPSVR__ArrayOfOutMessageFile ** SOAP_FMAC4 soap_in_PointerToCLIPSVR__ArrayOfOutMessageFile(struct soap*, const char*, CLIPSVR__ArrayOfOutMessageFile **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTotime
#define SOAP_TYPE_PointerTotime (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, std::vector<ns1__ProgramBasicEntityType * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, const std::vector<ns1__ProgramBasicEntityType * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, const char*, int, const std::vector<ns1__ProgramBasicEntityType * >*, const char*);
SOAP_FMAC3 std::vector<ns1__ProgramBasicEntityType * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, const char*, std::vector<ns1__ProgramBasicEntityType * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<ns1__ProgramBasicEntityType * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__ProgramBasicEntityType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint
#define SOAP_TYPE_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, std::vector<CLIPSVR__BreakPoint * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, const std::vector<CLIPSVR__BreakPoint * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, const char*, int, const std::vector<CLIPSVR__BreakPoint * >*, const char*);
SOAP_FMAC3 std::vector<CLIPSVR__BreakPoint * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, const char*, std::vector<CLIPSVR__BreakPoint * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(soap, n) soap_instantiate_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<CLIPSVR__BreakPoint * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerToCLIPSVR__BreakPoint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile
#define SOAP_TYPE_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, std::vector<CLIPSVR__OutMessageFile * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, const std::vector<CLIPSVR__OutMessageFile * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, const char*, int, const std::vector<CLIPSVR__OutMessageFile * >*, const char*);
SOAP_FMAC3 std::vector<CLIPSVR__OutMessageFile * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, const char*, std::vector<CLIPSVR__OutMessageFile * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(soap, n) soap_instantiate_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<CLIPSVR__OutMessageFile * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerToCLIPSVR__OutMessageFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
