//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EmbTaskOwl.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EmbTaskOwlTYPE              130
#define IDD_DLGSTGSETTING               310
#define IDD_DLGMANUALTASKSEARCH         311
#define IDD_DLGAUTOTASK                 312
#define IDD_DLGTEMPLATESETTING          313
#define IDD_DLG_OUTPUT                  314
#define IDD_DLG_NEWTASK                 315
#define IDD_DLGTOPBAR                   316
#define IDD_DLGPLAYLISTTASKSEARCH       317
#define IDR_MENU_TASKLISTPOP            317
#define IDD_DLG_MANUALADDEMBTASK        318
#define IDD_DIALOG_TEST                 319
#define IDD_DLG_TASKQUERY               320
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_PGMNAME                1001
#define IDC_EDIT3                       1002
#define IDC_BTN_NEW                     1002
#define IDC_EDIT_TYPE                   1002
#define IDC_BTN_EDIT                    1003
#define IDC_EDIT5                       1003
#define IDC_EDIT_FILENAME               1003
#define IDC_EDIT_DURATION               1003
#define IDC_BTN_DEL                     1004
#define IDC_EDIT_TYPE2                  1004
#define IDC_COMBO1                      1005
#define IDC_LIST_RELAY                  1005
#define IDC_EDIT_DURATION2              1005
#define IDC_COMBO2                      1006
#define IDC_BTN_COPY                    1006
#define IDC_COMBO_SECTION               1006
#define IDC_COMBO_CHNID                 1006
#define IDC_CMB_STG                     1006
#define IDC_EDIT_SRCID                  1007
#define IDC_CHECK1                      1008
#define IDC_BTN_MOVEUP                  1008
#define IDC_CHECK_TIMETOPLAYRANGE       1008
#define IDC_CHECKFILTER                 1008
#define IDC_EDIT4                       1009
#define IDC_BTN_MOVEDOWN                1009
#define IDC_CHECK_PLAYLISTRANGE         1009
#define IDC_CHECK7                      1009
#define IDC_EDIT_CLIPID                 1009
#define IDC_EDIT_LOG                    1009
#define IDC_CHECK2                      1010
#define IDC_BTN_ENABLE                  1010
#define IDC_CHECK_PGMCODE               1010
#define IDC_EDIT_INCOMINGTPL            1010
#define IDC_CHECK3                      1011
#define IDC_BUTTON1                     1011
#define IDC_CHECK_CLIPNAME              1011
#define IDC_BTN_CHANGECLIPID            1011
#define IDC_BTN_GETCONFIG               1011
#define IDC_CHECK4                      1012
#define IDC_LIST1                       1012
#define IDC_CHECK_CHID                  1012
#define IDC_LIST_LUAKT                  1012
#define IDC_CHECK5                      1013
#define IDC_LIST_STG                    1013
#define IDC_CHECK_EMERGNCY              1013
#define IDC_BTN_NEWTASK                 1013
#define IDC_EDIT_DB                     1013
#define IDC_LIST2                       1013
#define IDC_CHECK6                      1014
#define IDC_EDIT_STGCONTENT             1014
#define IDC_BTNTEST                     1014
#define IDC_CHECK_EMBSTATE              1014
#define IDC_EDIT_DB2                    1014
#define IDC_LIST3                       1014
#define IDC_LIST_TASK                   1015
#define IDC_EDIT_PLAYTIMEMAX            1016
#define IDC_LIST4                       1017
#define IDC_EDIT_PLAYLISTMAX            1017
#define IDC_LIST_FTP                    1017
#define IDC_RICHEDIT_LOG                1019
#define IDC_STC_AUTOMSG                 1020
#define IDC_EDIT_AUTOLOG                1021
#define IDC_BTN_RUN                     1022
#define IDC_CHECK_SHOWADVSEARCH         1023
#define IDC_GROUP_SEARCH                1024
#define IDC_EDIT_PGMCODE                1025
#define IDC_EDIT_CLIPNAME               1026
#define IDC_EDIT_PGMCODE2               1026
#define IDC_EDIT_EMBTASKID              1026
#define IDC_EDIT_CHID                   1027
#define IDC_EDIT_EMERGNCY               1028
#define IDC_EDIT_CHID2                  1028
#define IDC_BTN_SEARCH                  1029
#define IDC_EDIT_FILE                   1029
#define IDC_EDIT_PLAYTIMEMIN            1030
#define IDC_EDIT_PLAYLISTMIN            1031
#define IDC_STATIC_DAY                  1032
#define IDC_RDO_AUTO                    1034
#define IDC_RDO_MANUAL                  1035
#define IDC_DATETIME_PLAYLIST           1035
#define IDC_RDO_PLAYLIST                1036
#define IDC_BTNSUBMIT                   1039
#define IDC_COMBO_TPL                   1040
#define IDC_STATIC_OUTPUT               1041
#define IDC_COMBO_CHN                   1042
#define IDC_STATIC_PSINFO               1043
#define IDC_TCODE_LENGTH                1044
#define IDC_TCODE_SOM                   1045
#define IDC_TCODE_EOM                   1046
#define IDC_DTIMEPGMPLAY                1047
#define IDC_LUA_TEST                    1048
#define IDC_DATETIME_TIME               1049
#define IDC_DATETIME_TIME2              1050
#define IDC_BTN_COMMIT                  1051
#define IDC_BTN_BROWSE                  1052
#define ID_32771                        32771
#define ID_LISTPOP_32772                32772
#define ID_MENU_LISTPOP_SUBMIT          32773
#define ID_PLAYLISTPOP_32774            32774
#define ID_PLAYLISTPOP_NEWEMBTASK       32775
#define ID_MENU_PLAYLISTPOP_NEWEMBTASK  32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
